version: '3.9'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'aerozen'
      MONGO_INITDB_ROOT_PASSWORD: '123456'
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - '6379:6379'
